"""
Django settings for Mosquee_Annuaire project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dj_database_url  # Pour lire l'URL de la base de données de Render
from pathlib import Path
import cloudinary
import cloudinary.uploader
import cloudinary.api  # <- Important !
from django.utils.translation import gettext_lazy as _


"""
Paramètres de configuration Django pour le projet [NOM DE VOTRE PROJET].
"""

# Charger les variables d'environnement depuis un fichier .env en développement
# À NE PAS FAIRE SUR RENDER (les variables sont déjà définies)
if os.environ.get('RENDER') != '1':
    try:
        from dotenv import load_dotenv
        load_dotenv()
        print("[OK] Variables d'environnement chargées depuis .env")
    except ImportError:
        print("[WARN] python-dotenv non installé. Variables non chargées.")




# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==================== SECURITÉ ====================

# SECURITY WARNING: gardez la clé secrète utilisée en production secrète !
SECRET_KEY = os.environ.get('SECRET_KEY', 'unsafe-secret-key')

# SECURITY WARNING: ne pas exécuter avec le mode debug activé en production !
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Configuration des hôtes autorisés (sécurité)
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'djamaa.dz',
    'www.djamaa.dz',
]

# Ajout automatique du domaine Render lorsqu'on est sur la plateforme
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    print(f"[OK] Hôte Render ajouté : {RENDER_EXTERNAL_HOSTNAME}")

# ==================== BASE DE DONNÉES ====================
# Configuration flexible pour MySQL local et PostgreSQL sur Render

if os.environ.get('RENDER', '') == '1':
    # CONFIGURATION POUR RENDER (PostgreSQL)
    print("[INFO] Chargement config base de données Render...")
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # CONFIGURATION POUR LE DÉVELOPPEMENT LOCAL (MySQL)
    print("[INFO] Chargement de la configuration base de données locale (MySQL)...")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ.get('LOCAL_DB_NAME', ''),
            'USER': os.environ.get('LOCAL_DB_USER', ''),
            'PASSWORD': os.environ.get('LOCAL_DB_PASSWORD', ''),
            'HOST': os.environ.get('LOCAL_DB_HOST', ''),
            'PORT': os.environ.get('LOCAL_DB_PORT', ''),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'connect_timeout': 300,
            },
            'CONN_MAX_AGE': 600,
        }
    }

# ==================== FICHIERS STATIQUES (WhiteNoise) ====================

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ==================== FICHIERS MÉDIA (Uploads) ====================

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ==================== AUTRES PARAMÈTRES ====================

cloudinary.config(
    cloud_name=os.environ.get('CLOUDINARY_CLOUD_NAME'),
    api_key=os.environ.get('CLOUDINARY_API_KEY'),
    api_secret=os.environ.get('CLOUDINARY_API_SECRET'),
    secure=True,

)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# --- 1. CONTRÔLE D'ACCÈS ET ENVIRONNEMENT ---


# --- 2. SÉCURITÉ DES COOKIES (Adaptative) ---
# Le flag "Secure" (HTTPS) s'active automatiquement uniquement en production
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# Protection contre le vol de session via JavaScript (Attaques XSS)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True

# Politique de partage des cookies (Standard recommandé)
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
LANGUAGE_COOKIE_PATH = '/'

# --- 3. SÉCURITÉ DES EN-TÊTES HTTP (Protection du navigateur) ---
# Empêche l'affichage du site dans une iframe (Protection Clickjacking)
X_FRAME_OPTIONS = 'DENY'

# Empêche le navigateur de deviner le type de fichier (Protection MIME)
SECURE_CONTENT_TYPE_NOSNIFF = True

# Active le filtre anti-XSS intégré aux navigateurs
SECURE_BROWSER_XSS_FILTER = True

# Contrôle les informations envoyées aux sites externes (Protection Referrer)
SECURE_REFERRER_POLICY = 'same-origin'

# 2. Configurer les langues
LANGUAGE_CODE = 'fr'

LANGUAGES = [
    ('fr', 'Français'),
    ('ar', 'العربية'),
    ('en', 'English'),
]

USE_I18N = True
USE_L10N = True

# 3. Emplacement des dossiers de traduction
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Application definition
INSTALLED_APPS = [
    'modeltranslation',
    'mosques',
    #'axes',             # On ajoute l'outil de sécurité
    'csp',
    'honeypot', # On active l'application
    'admin_honeypot',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # ... autres apps ...
    'cloudinary',
    'cloudinary_storage',
    'django.contrib.sites',  # Nécessaire pour set_language

]
# On définit un nom de champ qui ressemble à un vrai champ
HONEYPOT_FIELD_NAME = 'author_website_url'

# On ajoute le "cerveau" qui surveille les connexions
AUTHENTICATION_BACKENDS = [
    #'axes.backends.AxesBackend', # Surveille les échecs
    'django.contrib.auth.backends.ModelBackend', # Backend par défaut de Django
]

SITE_ID = 1

MODELTRANSLATION_DEFAULT_LANGUAGE = 'fr'
MODELTRANSLATION_LANGUAGES = ('fr', 'ar', 'en')
MODELTRANSLATION_FALLBACK_LANGUAGES = ('fr', 'ar', 'en')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'csp.middleware.CSPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',  # 1. D'abord les sessions
    'django.middleware.locale.LocaleMiddleware',  # 2. PUIS la langue (A RAJOUTER ICI)
    'django.middleware.common.CommonMiddleware',  # 3. Enfin le reste
    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'axes.middleware.AxesMiddleware',
]

ROOT_URLCONF = 'Mosquee_Annuaire.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Mosquee_Annuaire.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

TIME_ZONE = 'UTC'

USE_TZ = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 2. Configuration Cloudinary via code (juste après les imports)


# Cloudinary pour le stockage des photos
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
    #'UPLOAD_PRESET': os.environ.get('CLOUDINARY_UPLOAD_PRESET'),
}

# Définir Cloudinary comme storage par défaut
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Taille max d'upload (10MB)
MAX_UPLOAD_SIZE = 10485760  # 10MB en bytes


# Permet de chercher la langue dans les headers du navigateur du visiteur

# Cookie settings
LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_AGE = 31536000  # 1 year
LANGUAGE_COOKIE_PATH = '/'

# ================================================================
# --- SÉCURITÉ AXES (PROTECTION FORCE BRUTE) ---
# ================================================================

# Blocage après 3 tentatives échouées
AXES_FAILURE_LIMIT = 3

# Déblocage automatique après 2 heures
AXES_COOLOFF_TIME = 2

# Réinitialisation du compteur après connexion réussie
AXES_RESET_ON_SUCCESS = True


# → Bloque par combinaison utilisateur + adresse IP
AXES_LOCKOUT_PARAMETERS = ['username', 'ip_address']

# ================================================================
# --- SÉCURITÉ HTTPS & EN-TÊTES (PRODUCTION UNIQUEMENT) ---
# ================================================================
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000  # 1 an
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# --- CONFIGURATION CSP (ACTIVE EN LOCAL ET PROD) ---
CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": ("'self'",),

        "script-src": (
            "'self'",
            "https://cdn.jsdelivr.net",
            "https://code.jquery.com",
            "https://cdnjs.cloudflare.com",
            "https://unpkg.com",
            "'unsafe-inline'",
        ),

        "style-src": (
            "'self'",
            "https://cdn.jsdelivr.net",
            "https://cdnjs.cloudflare.com",
            "https://code.jquery.com",
            "https://unpkg.com",
            "'unsafe-inline'",
        ),

        "img-src": (
            "'self'",
            "data:",
            "https://res.cloudinary.com",
            "https://i.postimg.cc",
            "https://*.tile.openstreetmap.org",
            "https://unpkg.com",
            "https://flagcdn.com",
        ),

        "connect-src": (
            "'self'",
            "https://api.aladhan.com",
            "https://api.cloudinary.com",
            "https://cdn.jsdelivr.net",  # <-- Ajoute cette ligne
        ),

        "font-src": (
            "'self'",
            "https://cdn.jsdelivr.net",
            "https://cdnjs.cloudflare.com",
        ),
    }
}
