# Generated by Django 5.2.9 on 2026-01-22 01:29

import cloudinary.models
import django.db.models.deletion
import django_countries.fields
import mosques.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=100)),
                ('name_ar', models.CharField(blank=True, max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('continent', models.CharField(max_length=2)),
                ('flag_url', models.URLField(blank=True, default='', max_length=300)),
                ('flag', models.CharField(default='🏳️', max_length=150)),
                ('django_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('capital', models.CharField(blank=True, max_length=100)),
                ('population', models.BigIntegerField(default=0)),
                ('currency', models.CharField(blank=True, max_length=50)),
                ('gdp', models.FloatField(blank=True, null=True)),
                ('capital_fr', models.CharField(blank=True, max_length=100)),
                ('capital_ar', models.CharField(blank=True, max_length=100)),
                ('capital_en', models.CharField(blank=True, max_length=100)),
                ('currency_fr', models.CharField(blank=True, max_length=50)),
                ('currency_ar', models.CharField(blank=True, max_length=50)),
                ('currency_en', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['name_fr'],
            },
        ),
        migrations.CreateModel(
            name='Mosque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la mosquée')),
                ('country', models.CharField(default='Algérie', max_length=100, verbose_name='Pays')),
                ('international_region', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100, verbose_name='Ville/Commune')),
                ('village', models.CharField(blank=True, max_length=100, verbose_name='Village')),
                ('address', models.TextField(blank=True, verbose_name='Adresse précise')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, help_text='Ex: 36.752887 (Alger)', max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, help_text='Ex: 3.042048 (Alger)', max_digits=11, null=True, verbose_name='Longitude')),
                ('main_photo', cloudinary.models.CloudinaryField(blank=True, help_text='Photo principale de la mosquée', max_length=255, null=True, verbose_name='photo_principale')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('history', models.TextField(blank=True, verbose_name='Historique')),
                ('history_fr', models.TextField(blank=True, null=True, verbose_name='Historique')),
                ('history_ar', models.TextField(blank=True, null=True, verbose_name='Historique')),
                ('history_en', models.TextField(blank=True, null=True, verbose_name='Historique')),
                ('is_verified', models.BooleanField(default=False, help_text='Cocher pour afficher sur la carte', verbose_name='Vérifiée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': 'Mosquée',
                'verbose_name_plural': 'Mosquées',
                'ordering': ['-created_at', 'wilaya', 'city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MosqueWithPhotos',
            fields=[
            ],
            options={
                'verbose_name': '📸 Mosque photos',
                'verbose_name_plural': '📸 Mosque photos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mosques.mosque',),
        ),
        migrations.CreateModel(
            name='MosquePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, validators=[mosques.models.validate_image_size], verbose_name='image')),
                ('uploaded_by', models.CharField(default='Admin', max_length=100)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='mosques.mosque')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True)),
                ('name_fr', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wilayas', to='mosques.country')),
            ],
            options={
                'verbose_name': 'Wilaya',
                'verbose_name_plural': 'Wilayas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom de la mosquée')),
                ('city', models.CharField(max_length=100, verbose_name='Ville/Commune')),
                ('village', models.CharField(blank=True, max_length=100, verbose_name='Village')),
                ('address', models.TextField(blank=True, verbose_name='Adresse précise')),
                ('country', models.CharField(default='Algérie', max_length=100, verbose_name='Pays')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('description_fr', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('history', models.TextField(blank=True, verbose_name='Historique')),
                ('history_fr', models.TextField(blank=True, null=True, verbose_name='Historique')),
                ('history_ar', models.TextField(blank=True, null=True, verbose_name='Historique')),
                ('history_en', models.TextField(blank=True, null=True, verbose_name='Historique')),
                ('photos', models.TextField(blank=True, help_text='URLs Cloudinary séparées par des virgules', verbose_name='Photos')),
                ('contributor_email', models.EmailField(blank=True, max_length=254, verbose_name='Email du contributeur')),
                ('contributor_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de proposition')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de modération')),
                ('review_notes', models.TextField(blank=True, verbose_name='Notes du modérateur')),
                ('wilaya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosques.wilaya', verbose_name='Wilaya')),
            ],
            options={
                'verbose_name': 'Proposition',
                'verbose_name_plural': 'Propositions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mosque',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosques.wilaya', verbose_name='Pays/Wilaya'),
        ),
    ]
