# Generated by Django 5.2.9 on 2026-01-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='language_ar',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='language_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='language_fr',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
