# Generated by Django 5.2.9 on 2026-01-28 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0002_country_language_ar_country_language_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mosque',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='mosque',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='mosque',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='mosque',
            name='history_ar',
        ),
        migrations.RemoveField(
            model_name='mosque',
            name='history_en',
        ),
        migrations.RemoveField(
            model_name='mosque',
            name='history_fr',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='history_ar',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='history_en',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='history_fr',
        ),
        migrations.AddField(
            model_name='mosque',
            name='country_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosques.country', verbose_name='Pays (Sélectionner)'),
        ),
    ]
