# Generated by Django 5.2.9 on 2026-01-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0003_remove_mosque_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='mosque',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='mosque',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='mosque',
            name='history_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Historique'),
        ),
        migrations.AddField(
            model_name='mosque',
            name='history_en',
            field=models.TextField(blank=True, null=True, verbose_name='Historique'),
        ),
        migrations.AddField(
            model_name='mosque',
            name='history_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Historique'),
        ),
        migrations.AddField(
            model_name='proposition',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='proposition',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='proposition',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='proposition',
            name='history_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Historique'),
        ),
        migrations.AddField(
            model_name='proposition',
            name='history_en',
            field=models.TextField(blank=True, null=True, verbose_name='Historique'),
        ),
        migrations.AddField(
            model_name='proposition',
            name='history_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Historique'),
        ),
    ]
