# Generated by Django 5.1.15 on 2026-02-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0004_mosque_description_ar_mosque_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosquephoto',
            name='caption',
            field=models.CharField(blank=True, help_text='Optionnel : description ou légende de la photo', max_length=250, null=True),
        ),
    ]
