# Generated by Django 5.1.15 on 2026-02-16 00:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0005_mosquephoto_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='photos',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Photo de la proposition'),
        ),
    ]
