# Generated by Django 5.1.15 on 2026-02-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0006_alter_proposition_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='photos',
            field=models.TextField(blank=True, help_text="Stocke l'URL ou la signature Cloudinary sans limite de taille", null=True, verbose_name='Photos (URL Cloudinary)'),
        ),
    ]
