# Generated by Django 5.1.15 on 2026-02-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0007_alter_proposition_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='photos',
            field=models.TextField(blank=True, help_text='URLs Cloudinary séparées par des virgules', null=True, verbose_name='Photos (URL Cloudinary)'),
        ),
    ]
