# Generated by Django 5.1.15 on 2026-02-16 01:15

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0008_alter_proposition_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosquephoto',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='photos',
            field=models.TextField(blank=True, null=True, verbose_name='Photos (URL Cloudinary)'),
        ),
    ]
