# Generated by Django 5.1.15 on 2026-02-19 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0009_alter_mosquephoto_image_alter_proposition_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropositionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='URL de la photo Cloudinary')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_list', to='mosques.proposition')),
            ],
        ),
    ]
