# Generated by Django 5.1.15 on 2026-02-20 03:35

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0010_propositionphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propositionphoto',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='propositionphoto',
            name='image_url',
        ),
        migrations.AddField(
            model_name='propositionphoto',
            name='image',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propositionphoto',
            name='proposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposition_photos', to='mosques.proposition'),
        ),
    ]
