# Generated by Django 5.1.15 on 2026-02-22 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0011_rename_uploaded_at_propositionphoto_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='photos',
        ),
        migrations.AlterField(
            model_name='mosque',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mosques.wilaya', verbose_name='Wilaya'),
        ),
    ]
