# Generated by Django 5.1.15 on 2026-02-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0012_remove_proposition_photos_alter_mosque_wilaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Nom de la mosquée'),
        ),
        migrations.AddField(
            model_name='mosque',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Nom de la mosquée'),
        ),
        migrations.AddField(
            model_name='mosque',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Nom de la mosquée'),
        ),
    ]
