# Generated by Django 5.1.15 on 2026-02-22 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0013_mosque_name_ar_mosque_name_en_mosque_name_fr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mosque',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='mosque',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='mosque',
            name='name_fr',
        ),
    ]
