# Generated by Django 5.1.15 on 2026-02-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0014_remove_mosque_name_ar_remove_mosque_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Nom de la mosquée'),
        ),
        migrations.AddField(
            model_name='mosque',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Nom de la mosquée'),
        ),
        migrations.AddField(
            model_name='mosque',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='Nom de la mosquée'),
        ),
    ]
