# Generated by Django 5.1.15 on 2026-02-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0015_mosque_name_ar_mosque_name_en_mosque_name_fr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosque',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de la mosquée'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='name_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de la mosquée'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de la mosquée'),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='name_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom de la mosquée'),
        ),
    ]
