# Generated by Django 5.1.15 on 2026-02-25 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosques', '0016_alter_mosque_name_alter_mosque_name_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_method', models.CharField(default='MWL', max_length=50, verbose_name='Méthode de calcul')),
                ('fajr_offset', models.IntegerField(default=0, verbose_name='Ajustement Fajr (min)')),
                ('dhuhr_offset', models.IntegerField(default=0, verbose_name='Ajustement Dhuhr (min)')),
                ('asr_offset', models.IntegerField(default=0, verbose_name='Ajustement Asr (min)')),
                ('maghrib_offset', models.IntegerField(default=0, verbose_name='Ajustement Maghrib (min)')),
                ('isha_offset', models.IntegerField(default=0, verbose_name='Ajustement Isha (min)')),
                ('mosque', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prayer_settings', to='mosques.mosque')),
            ],
        ),
    ]
